import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./utils/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      minWidth: {
        75: "325px",
      },
      screens: {
        mobile: "400px",
        "1xMobile": "450px",
        "2xMobile": "520px",
        "3xMobile": "660px",
        features: "1000px",
        lgx: "1081px",
        about: "1200px",
        xs: "580px",
        xsm: "585px",
        "1xs": "600px",
        "2xs": "700px",
        "1lgx": "1005px",
        "2lgx": "1025px",
        "1xl": "1200px",
        mdx: "820px",
        "1mdx": "889px",
      },
      letterSpacing: {
        lt: "var(--letter-base)",
      },
      backgroundColor: {
        featuresOne: "var(--bg-features-one)",
        featuresTwo: "var(--bg-features-two)",
        featuresThree: "var(--bg-features-three)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        roboto: ["var(--font-roboto)"],
        philosopher: ["var(--font-philosopher)"],
      },
      fontSize: {
        features: "31px",
        featuresItem: "25px",
        aboutSize: "31px",
        menu: "31px",
        cardSize: "25px",
        appSize: "31px",
        testimonial: "31px",
        contactSize: "31px",
      },
      colors: {
        primary: "var(--primary-color)",
        header: "var(--header-color)",
        about: "var(--about-color)",
        menuColor: "var(--menu-color)",
        application: "var(--application)",
        appStore: "var(--app-store-bg)",
        contact: "var(--contact)",
        footer: "var(--footer)",
      },
      margin: {
        1.2: "5px",
        2.4: "9px",
        3.5: "15px",
        4.5: "18px",
        5.1: "21px",
        6.5: "25px",
        6.8: "26px",
        7.1: "29px",
        7.5: "30px",
        8.5: "33px",
        10.5: "42px",
        11.5: "46px",
        13: "50px",
        14.5: "60px",
        15.5: "70px",
        30: "120px",
        47: "187px",
      },
      padding: {
        2.6: "11px",
        3.5: "14px",
        4.5: "18px",
        6.5: "25px",
        7.5: "30px",
        8.5: "35px",
        29: "115px",
      },
      gap: {
        7.5: "30px",
        18.5: "73px",
        features: "90px",
        application: "70px",
      },
      lineHeight: {
        3.5: "14px",
        4.5: "19px",
        48: "48px",
        features: "35px",
        about: "40px",
        application: "40px",
      },
      borderColor: {
        primary: "var(--border-color)",
        button: "var(--border-button-color)",
        dark: "var(--border-dark-color)",
      },
      borderWidth: {
        1.5: "1.5px",
      },
    },
    letterSpacing: {
      md: "var(--letter-md)",
    },
  },
  plugins: [],
};
export default config;
