import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Philosopher } from "next/font/google";

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700', '900']
});

const philosopher = Philosopher({
  subsets: ['latin'],
  variable: '--font-philosopher',
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Health Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${philosopher.variable}`}>{children}</body>
    </html>
  );
}
